### ISSUE TITLE
Create Subspace Booster Antenna

### ISSUE THREAD

**Issue by DraksterAU** [StargateMC/Server#143]
**Character Name In-game**

Bysokar

**Description**

Creation of a way to boost Kino Remote signal is required

**Current Behaviour**

Currently Kino remotes are restricted to same-galaxy information. This should be expanded based on power or some other factor to allow Kinos to pick up gates in other galaxies.

**Expected Behaviour**

A Subspace Antenna Booster should be placed down, with a formation of steel bars above it and look similar to a lightning rod. The only difference is this will boost the signal of nearby Kinos, rather than draw energy from lightning.

**Tasks**

- [ ] Creation of Subspace Antenna Block
- [ ] Creation of Subspace Antenna Tile Entity
- [ ] Creation of isFormed flag in the TE, which triggers when there are 8 steel bars above the block and nothing but air above that.
- [ ] Have the TE draw energy every time a Kino is used nearby as it relays information further into the universe
- [ ] The more power in the buffer and taller the antenna, the further into the universe the antenna can reach, with a hard cap of 50%.

**Crash Reports and Logs Attached?**

N/A

**Is this happening in singleplayer or multiplayer?**

N/A

**Client Modpack Version**

N/A
