### ISSUE TITLE
Create Random Incursion Events

### ISSUE THREAD

**Issue by DraksterAU** [StargateMC/Server#144]
**Character Name In-game**

Bysokar

**Description**

A Random dial-in event with mobs spawning would be cool, allowing for incursion events.

**Current Behaviour**

None.

**Expected Behaviour**

Dependant on the galaxy you are in, Wraith, Haaken, Goauld, Rogue Jaffa or Ori Priors should dial into a world and spawn there. If there is noone to attack, they should despawn after 10 minutes.

Logically this will be a random dial event that can be triggered on the destination gate only and then spawn events for npcs just outside the stargate.

This should have a small chance to spawn a friendly NPC that has goods that a player could buy.

**Tasks** 

- [x] Create random event that triggers a stargate to dial nowhere based on a timer, or another gate being active.
- [x] Create a away to spawn a specific NPC at a specific location in a specific world and tie this in with the dial event
- [x] Create a way for the NPCs to be force-despawned after 10 minutes

**Crash Reports and Logs Attached?**

N/A

**Is this happening in singleplayer or multiplayer?**

Multiplayer

**Client Modpack Version**

N/A
